version: '1.0'
services:
  nginx:
    image: nginx
    env:
      TZ: "UTC"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app_network
  backend:
    build:
      context: ./backend
    env_file: .env
    environment:
      NODE_ENV: production
    command: npm start
    depends_on:
      - mongo
    networks:
      - app_network
  frontend:
    build:
      context: ./frontend
    env_file: .env
    environment:
      INFISICAL_TELEMETRY_ENABLED: ${TELEMETRY_ENABLED}
      NEXT_PUBLIC_STRIPE_PRODUCT_PRO: ${STRIPE_PRODUCT_PRO}
      NEXT_PUBLIC_STRIPE_PRODUCT_TEAM: ${STRIPE_PRODUCT_TEAM}
      NEXT_PUBLIC_STRIPE_PRODUCT_STARTER: ${STRIPE_PRODUCT_STARTER}
    depends_on:
      - backend
    networks:
      - app_network
  mongo:
    image: mongo
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - app_network
networks:
  app_network:
volumes:
  mongo-data:
