services:
  nginx:
    environment:
      - TZ=UTC
    image: nginx
    ports:
      - 80:80
      - 443:443
    secrets:
      - name: nginx-default-conf
        mountPath: /etc/nginx/conf.d/default.conf
        readOnly: true
    dependsOn:
      - frontend
      - backend
    networks:
      - infisical

  backend:
    image: infisical/backend
    env:
      NODE_ENV: production
    secrets:
      - name: env
    dependsOn:
      - mongo
    networks:
      - infisical

  frontend:
    image: infisical/frontend
    env:
      INFISICAL_TELEMETRY_ENABLED: ${TELEMETRY_ENABLED}
      NEXT_PUBLIC_STRIPE_PRODUCT_PRO: ${STRIPE_PRODUCT_PRO}
      NEXT_PUBLIC_STRIPE_PRODUCT_TEAM: ${STRIPE_PRODUCT_TEAM}
      NEXT_PUBLIC_STRIPE_PRODUCT_STARTER: ${STRIPE_PRODUCT_STARTER}
    secrets:
      - name: env
    dependsOn:
      - backend
    networks:
      - infisical

  mongo:
    image: mongo
    env:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - name: mongo-data
        mountPath: /data/db
    networks:
      - infisical

secrets:
  nginx-default-conf:
    externalRef: 
      name: nginx-default-conf
  env:
    externalRef: 
      name: env

volumes:
  mongo-data:
    mountPath: /data/db

networks:
  infisical:
